version: '3.7'
services:
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - "/var/www:/var/www"

    web:
        build: ./web
        container_name: web
        restart: always
        expose:
            - 9000
        volumes:
            - "/var/www:/var/www"
