version: '3.7'
services:
    site:
        build: .
        image: site
        container_name: site
        restart: always
        ports:
            - "80:8000"
        volumes:
            - /var/www:/var/www

    nginx:
        image: nginx
        container_name: nginx
        depends_on:
            - site
