version: '3.7'
services:
    web:
        build: .
        image: site
        container_name: site
        restart: always
        volumes:
            - /var/www:/var/www
        ports:
            - "80:8000"
