version: '3.7'
volumes:
    sock:
services:
    site:
        build: .
        image: site
        container_name: site
        restart: always
        volumes:
            - sock:/sock

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "8000:8000"
        volumes:
            - sock:/sock
            - /var/www/screenshots:/var/www/screenshots
            - /var/www/files:/var/www/files
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - site
