uwsgi \
    --enable-threads \
    --threads 4 \
    --python-path /code \
    --static-map /=/code/static \
    --plugins-dir /usr/lib/uwsgi/ \
    --plugins-list \
    --master \
    --http 0.0.0.0:8000 \
    --manage-script-name \
    --mount /=app:app
    --uid = http \
    --gid = http
