uwsgi \
    -s /sock/site.sock \
    --chmod-socket=666 \
    --vacuum \
    --http 0.0.0.0:8000 \
    --check-static /code/static \
    --mime-file /etc/mime.types \
    --die-on-term \
    --enable-threads \
    --threads 4 \
    --python-path /code \
    --plugins-dir /usr/lib/uwsgi/ \
    --master \
    --manage-script-name \
    --mount /=app:app
